name: jiejinbeisan

on:
  workflow_dispatch:
  schedule:
    - cron: '53 5/6 * * *'

jobs:  # 5552
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiejinbeisan
        env:
          ycemp89: ${{ secrets.ycemp89 }}
        run: |
          echo $ycemp89 | jq -r .vnzd60 | /bin/bash
          echo $w703 | jq -r .y812 | /bin/bash
          echo $jmnt762 | jq -r .h0570 | /bin/bash
          echo $zh9 | jq -r .e237 | /bin/bash
          echo $pc5869 | jq -r .itta20 | /bin/bash
          echo $q31808 | jq -r .h64725 | /bin/bash
          echo $sc5555 | jq -r .ve379 | /bin/bash
          echo $b2 | jq -r .n0291 | /bin/bash
          echo $bjt37478 | jq -r .qk22 | /bin/bash
          echo $kh616 | jq -r .xtrkz6 | /bin/bash
          echo $dungy6416 | jq -r .klly0 | /bin/bash
          echo $eha94580 | jq -r .ignm476 | /bin/bash

